### ISSUE TITLE
Support MiniKube with different drivers

### ISSUE THREAD

**Issue by mstrangfeld** [tilt-dev/ctlptl#310] opened 2023-09-05 15:57 UTC
For testing some applications it is very useful if you could specify the driver for the minikube cluster like `kvm2`, for example.

**Comment by nicks** [comment] 2023-09-05 16:01
thanks for the report! i'm going to mark this as a duplicate of https://github.com/tilt-dev/ctlptl/issues/93

**Closed by nicks** 2023-09-05 16:01 UTC
